### PR TITLE
Update pymc dependency to version 5.19

### PR DESCRIPTION
**Pull request by cpaniaguam**
This pull request includes updates to dependencies in the `pyproject.toml` file. Namely, it updates of the `pymc` dependency to a newer version. 

Dependency updates:

* `pyproject.toml`: Updated the `pymc` dependency from ">=5.16.2,<5.17.0" to "^5.19".

The goal is to ensure this version is compatible with `hssm` and further investigate #608.

### CODE REVIEW

**Comment by AlexanderFengler** [comment]
@cpaniaguam what's going on with the tests here? Running for over 3h :0

**Comment by cpaniaguam** [comment]
> @cpaniaguam what's going on with the tests here? Running for over 3h :0

@AlexanderFengler there seems to be a problem with pymc v.5.19 and the environments with Python v.3.10/12. I can't get it to install properly in those environments locally and it seems like in ci gets hung up. @digicosmos86 any ideas?

**Comment by cpaniaguam** [comment]
> @cpaniaguam what do you mean you can't install PyMC 5.19 locally?

Oh sorry, I meant that I can't install `hssm` with `pymc` v5.19 in environments with Python 3.10/12 on my computer using WSL.

**Comment by AlexanderFengler** [comment]
@digicosmos86 will look at the outputs, but it's a bit weird. Not getting those problems on my PRs. (slow tests ~30min)

**Comment by digicosmos86** [comment]
> @digicosmos86 will look at the outputs, but it's a bit weird. Not getting those problems on my PRs. (slow tests ~30min)

@AlexanderFengler Yeah checked with Carlos about it but it seems that some tests just consistently fail after only updating PyMC. That's why we are moving to `uv` which allows us to create environments with different python versions so we can test these things locally

**Comment by AlexanderFengler** [comment]
Taken care of in the context of #607 now.
Not entirely sure what the rootcause was, but I upgrade a couple version restrictions and tests are passing. @cpaniaguam @digicosmos86

**Pull request closed without merging**
