### PR TITLE
Fix `nuts_numpyro` sampling error with regressions

### PR DESCRIPTION
**Pull request by digicosmos86**

### CODE REVIEW

**Review by AlexanderFengler — COMMENTED** [review]
looks good, not sure what / why tests are failing...

**Comment by AlexanderFengler** [comment]
I see the failed test concern an equality test on some tensors. 
Likely the test where you check if jax / pytensor likelihoods produce the same outputs?

**Comment by digicosmos86** [comment]
> I see the failed test concern an equality test on some tensors. Likely the test where you check if jax / pytensor likelihoods produce the same outputs?

This is fixed. By making all tests consistent (testing equal to 4 decimals) all tests passed.

**Comment by AlexanderFengler** [comment]
So you put this down to cumulative rounding errors with float32?

**Comment by AlexanderFengler** [comment]
> > So you put this down to cumulative rounding errors with float32?
> 
> I believe so. Also it was passing on my laptop, so platform differences could also be a reason

argh. Ok not too satisfying (slightly scary) but ok or now :)

**Review by AlexanderFengler — APPROVED** [review]
approved

**Pull request merged**
