### PR TITLE
Fix `Param` creation and update docs for `v0.1.1` release

### PR DESCRIPTION
**Pull request by digicosmos86**
The PR addresses the following issues:

#186
Parameters specified in `include` with `bounds` was not parsing correctly. Fixed this problem in `hssm.py` and `param.py`.

#157 
Added some animation that points the users to the collapsed navigation bar on smaller screens.
image

Also updated the documentation.

@AlexanderFengler I moved your 006 notebook to `docs/notebooks` together with the images. However, the images are not rendered correctly. Can you take a look at `docs/notebooks/main_tutorial.ipynb`?

### CODE REVIEW

**Comment by AlexanderFengler** [comment]
hm that's a weird one. 
it renders fine on local :/.

**Comment by AlexanderFengler** [comment]
ok got it, the fix is to put the images in another folder (not sure why but mkdocs seems to do it this way)
so where the `main_tutorial.ipynb` notebook is, you add a `main_tutorial` folder, then in there put `images/...`.

mkdocs seems to automatically extend the `images/...png` into `main_tutorial/images/...png`. 

pushed this now (including some unnecessary inflation of images which we can erase again.

**Comment by digicosmos86** [comment]
Pulled your commit and it works great on my end now :)

**Review by AisOmar — APPROVED** [review]
looks good

**Review by AlexanderFengler — APPROVED** [review]
ok

**Pull request merged**
